-- Init user

-- CREATE DATABASE ... [REBUILD10]
CREATE USER "REBUILD" IDENTIFIED BY "REBUILD";
GRANT CREATE SESSION, RESOURCE, CONNECT TO "REBUILD";
-- ALTER USER "REBUILD" ACCOUNT LOCK | UNLOCK
-- DROP USER "REBUILD"

-- Init data

