# ConfigurationItem
TrustedAllUrl=
LibreofficeBin=
MysqldumpBin=
UnsafeImgAccess=
SecurityEnhanced=
_SmsDistributor=
_EmailDistributor=
_UseFrontJSAnywhere=
_TriggerMaxDepth=
_ImageBigThumb=
_ImageWatermark=